### ISSUE TITLE
MSC-new design 5.2 Dark mode not choosing correct .css colors macOS Big Sur

### ISSUE THREAD

**Issue by lifeunexpected** [munki/munki#1060] opened 2020-11-25 13:37 UTC
Version 5.2 munkitools-5.2.0.4240

When you have dark mode enabled colors from base.css, detail.css and  files are ignored and not used and instead it uses default light mode text colors.

Normally " html[data-theme='dark']  "and the colors set should be used but instea the default colors are used
This causes text to be almost impossible to see since they are become dark text on dark backgrounds.

<img width="493" alt="Screenshot 2020-11-25 at 14 29 52" src="https://user-images.githubusercontent.com/36742392/100234660-b1526b80-2f2b-11eb-9769-e4d9cc015714.png">
<img width="1239" alt="Screenshot 2020-11-25 at 14 31 01" src="https://user-images.githubusercontent.com/36742392/100234668-b31c2f00-2f2b-11eb-8be8-83d7f2f50f61.png">

**Comment by gregneagle** [comment] 2020-11-25 14:26
I’m not seeing that here on any of my test machines.  MSC looks as expected/desired in Dark Mode. 

Have you done any client customization?

**Comment by gregneagle** [comment] 2020-11-25 17:39
<img width="960" alt="image" src="https://user-images.githubusercontent.com/700560/100263165-011c3d00-2f02-11eb-9b8f-12999c9f9ed1.png">

<img width="948" alt="image" src="https://user-images.githubusercontent.com/700560/100263222-12fde000-2f02-11eb-9010-6712a3dd1a25.png">

**Comment by lifeunexpected** [comment] 2020-11-26 12:49
It looks correct on macOS Catalina and Mojave and older versions probably as you can see on the picture below
![image](https://user-images.githubusercontent.com/36742392/100349587-fa1c2a00-2fe8-11eb-8321-5b9ae59b572d.png)

I tried it on 2 real machines and 1 virtual machine but same problem happens when i use macOS Big Sur.

![image](https://user-images.githubusercontent.com/36742392/100350380-153b6980-2fea-11eb-877d-bb7cde9f746f.png)

Tried uninstalling MSC multiple times and formated and re-installed macOS Big Sur on one of the mac since its my test machine.

I disabled and removed my client customization but same problem happens. 
The client customization file i use contain custom pictures and text but nothing that should change the colors and the client customization file do work properly on macOS catalina and earlier OS versions with Munki 5.2

**Comment by gregneagle** [comment] 2020-11-26 14:50
Not seeing it on Big Sur:
![image](https://user-images.githubusercontent.com/700560/100364871-87dd2280-2fb3-11eb-848b-18ff8647d59d.png)

**Comment by opragel** [comment] 2020-11-30 02:19
Seeing the same issue here without any customization on Big Sur Intel and ARM devices, latest release (5.2.0.4240).

**Comment by gregneagle** [comment] 2020-11-30 04:19
Until there's a way for me to reproduce this, there's not much I can do to address it. In my testing, it works as expected on Big Sur.

**Comment by lifeunexpected** [comment] 2020-12-02 10:31
Think i found out what is wrong and maybe a way for you too see what is wrong and why it works for you @gregneagle.

How to replicate: 
1: First Enable the HTML Web Inspector 
https://github.com/munki/munki/wiki/Client-Customization#enable-the-html-web-inspector

2: Open Managed Software Center

3: Right click on any area in MSC and click "inspect element"

4: If you look at data-theme="light" it doesnt change to data-theme="dark" on macOS 11.0 Big Sur for me but it does it on macos 10.15 Catalina

<html lang="en" data-theme="light" class=""><head>
![image](https://user-images.githubusercontent.com/36742392/100858880-d47e9d00-348e-11eb-86e8-6349ee7ba459.png)

If you open "System Preferences" --> Open "General" --> Go to "Apperance" and switch between light and dark mode and see if data-theme="light" changes to data-theme="dark" you use dark mode and then back to data-theme="light" if you switch back to light mode.

For me data-theme="light" wont change when i enable dark mode on macOS Big Sur 11.0 but if i manually change data-theme="light" to dark the colors/theme changes to what its supposed to be.

I thought first it was my default web browser but i tried changing it to Safari, Chrome and firefox but same thing happend.

**Comment by securitygeneration** [comment] 2020-12-02 13:50
fwiw, I'm experiencing the same issue on Big Sur

![image](https://user-images.githubusercontent.com/1046239/100881014-bb391900-34ad-11eb-8e7e-f2c5ce407b70.png)

**Comment by dev-yeet** [comment] 2020-12-02 15:14
for me it looked like this due to building with xcode 12 on catalina. if you download an older version (like say from developer.apple.com), it will work fine. least it did in my case.

**Comment by gregneagle** [comment] 2020-12-02 15:17
Has everyone seeing this built their own installer pkg from source? 
If so, what happens if you install the release package from this GitHub repo?

**Comment by securitygeneration** [comment] 2020-12-02 15:58
I'm building with `Xcode 12.2 Build version 12B5035g`

@gregneagle someone on Slack who has this issue is using the autopkg recipes.

For my part I can't use the release package from GitHub yet (just because I currently hack the script to include my middleware files, and an additional Python dependency, in the final package - I'm aware I need to somehow fix this so that I can start relying on the raw release packages).

But, for the sake of testing, I went ahead and installed the GitHub package, and MSC looks normal:

![image](https://user-images.githubusercontent.com/1046239/100896658-25a68500-34bf-11eb-9892-633885dea48c.png)

After installing using the GitHub package, I re-installed using my own package (to get my middleware setup working again)... and now MSC still looks normal. So consider me confused.

**Comment by gregneagle** [comment] 2020-12-02 16:02
This was built using Xcode 12.2 on Big Sur, and looks fine under Dark Mode on Big Sur:

![image](https://user-images.githubusercontent.com/700560/100897516-9eccba80-3474-11eb-88a4-0645fa04c527.png)

So while there are some clues, we still don't have a reliable reproducer.

**Comment by gregneagle** [comment] 2020-12-03 00:56
All: when your Mac is in Dark Mode, and MSC.app is exhibiting this issue, what is the output of
`defaults read -g AppleInterfaceStyle` ?

It should be:
```
$ defaults read -g AppleInterfaceStyle
Dark
```

**Comment by sethgoldin** [comment] 2020-12-03 02:29
FWIW, I _am_ seeing this issue on my Big Sur test VM, from a build of 5.2 that I had built in Catalina. I built it with Xcode 12.2 (12B45b) on macOS 10.15.7 (19H15) with the `-R`, `-n`, and `-m`.

Upon trying to open Xcode to check the version just now, it prompted me for some "additional components," but not sure if that affects the versioning or this issue.

`% defaults read -g AppleInterfaceStyle` returns `Dark` for me in the 11.0.1 VM.

**Comment by lifeunexpected** [comment] 2020-12-04 07:51
I see $ defaults read -g AppleInterfaceStyle
Dark

When i install the munkitools-5.2.0.4240.pkg that you have packaged dark mode works correctly and the theme changes when i switch between light and dark mode.

I package it on:
MacOS big Sur  11.0.1
Xcode 12.2 12B45B

Normally i package munki with https://github.com/lifeunexpected/Scripts MunkiPythonNotarizeAndSign.zsh that signs and notarize the app but this runs make_run_mpkg.sh  

I also tried to use "make_run_mpkg.sh" and "make_munki_mpkg_from_git.sh" and the same problem with dark mode not working correctly still is there.

Maybe something then is broken when its packaged? :/

**Comment by gregneagle** [comment] 2020-12-04 13:48
> Maybe something then is broken when its packaged?

Well, no, it’s not that simple, as I use `./make_munki_mpkg_from_git.sh` to build the packages I post on GitHub.

**Comment by securitygeneration** [comment] 2020-12-04 15:44
@gregneagle how do you do this for a specific branch/tag/release using that script (i.e. what command do I run to build a 5.2.0 package)? I could try to run mine using that script instead of the `make_munki_mpkg.sh`

**Comment by poundbangbash** [comment] 2020-12-04 15:56
`./code/tools/make_munki_mpkg_from_git.sh -b universal2`
Or to build a specific commit/tag: `./code/tools/make_munki_mpkg_from_git.sh -b v5.3.0a2` )

**Comment by dev-yeet** [comment] 2020-12-04 16:03
i guess i wasn't super specific but anyone still building on catalina that is having issues with the dark theme on big sur, try building with xcode 11.7 on Catalina. At the time, the latest xcode suggested by greg in the wiki was xcode 11.

**Comment by gregneagle** [comment] 2020-12-04 16:09
The 5.2.0 release package was built with Xcode 11.7 on macOS 10.15.7.
The 5.3 super early universal2 builds packages were built with Xcode 12.2 on macOS 11.0.1 (Intel).

I don't see the reported Dark Mode issues when installing either of these.

Perhaps the issue happens with Xcode 12 on Catalina?

**Comment by sethgoldin** [comment] 2020-12-05 21:39
I may be able to test with Xcode 11.7 on macOS 10.15.7 next week. Will this just be a recommendation going forward, or might I expect to be able to use 12.2 on 10.15.7 at some point?

**Comment by gregneagle** [comment] 2020-12-06 04:40
We are in data collection mode here. There are no official recommendations.

**Comment by lifeunexpected** [comment] 2020-12-07 10:49
This is interesting and i would like more people to test this
Since Greg said 
> The 5.2.0 release package was built with Xcode 11.7 on macOS 10.15.7.

 I tried the same using" make_munki_mpkg_from_git.sh -b v5.2.0" with Xcode 11.7 on macOS 10.15.7 and now the theme colors change correctly when i install the package i built on macOS Big Sur.

I have not been able to test the super early 5.3 universal2 builds on Mac ARM since i'm still waiting on getting my new machine so hopefully someone else can test this and see if the dark mode issue is happening here.

So my question is if more people is able  to test if dark mode works correctly if you  package it with Xcode 11.7 and macOS 10.15.7. It might work with other versions also but these are the latest versions before Xcode 12 and macOS Big Sur.

**Comment by gregneagle** [comment] 2020-12-07 18:39
I finally replicated the issue and I believe it's fixed in the code repo; I'll release a 5.2.1 soon.

This turns out to have nothing to do with the build OS or version of Xcode used, though it's possible that certain combinations of build OS and Xcode version might have hidden the ultimate bug here.

This boils down to OS version checking and Apple's move from 10.10, 10.12, 10.13 pattern where you basically ignored the "major os version" (10) and compared against the "minor os version" (10,12,13,etc).

The reason I never saw the issue goes back to when I was first adding support for Dark Mode _before_ Mojave shipped. I added a special preference you could set in com.googlecode.munki.ManagedSoftwareCenter: AllowDarkModeOnUnsupportedOSes -- which allowed one to "try out" Dark Mode support on 10.13, for example. This was set on my machine, and when this preference is set, the OS comparison result is ignored.

Others might have not seen this bug if they built MSC.app on Catalina with Xcode 11.7, because in that case (where the app is built against the 10.15 SDK instead of the Big Sur SDK), the OS may report its version as 10.16.x to the requesting code. (This would cause the version comparison to behave as expected.)

The fix was to move to a better way of checking "are we on at least this OS" that is not tripped up by the OS version "style change".

**Closed by gregneagle** 2020-12-07 18:39 UTC

**Comment by securitygeneration** [comment] 2020-12-09 13:57
Just wondering if this fixed it for others, as I built a fresh pkg from 5.2.1 source, pushed it to affected devices, and the issue persists:

![image](https://user-images.githubusercontent.com/1046239/101638786-cdc3cd00-3a2e-11eb-869d-5d5e68e8cfd0.png)

**Comment by dev-yeet** [comment] 2020-12-09 14:01
does this happen even if you uninstall munki completely? [Uninstall](https://github.com/munki/munki/wiki/Removing-Munki)

Also what version of xcode did you build with and what os? 

> Just wondering if this fixed it for others, as I built a fresh pkg from 5.2.1 source, pushed it to affected devices, and the issue persists:
> 
> ![image](https://user-images.githubusercontent.com/1046239/101638786-cdc3cd00-3a2e-11eb-869d-5d5e68e8cfd0.png)

**Comment by securitygeneration** [comment] 2020-12-09 14:47
No, haven't tried fully removing it yet.

I'm building from 5.2.1 source using Xcode 12.2 Build version 12B5035g on macOS 11.0.1 (Intel)
