### ISSUE TITLE
Feature request - manual update should install what it can

### ISSUE THREAD

**Issue by ofirgalcon** [munki/munki#1156] opened 2022-08-31 00:39 UTC
If I run managedsoftwareupdate --auto munki installs what it can. If some updates require quitting apps or restarting, it just skips these and installs the rest.

It would be great to have the same behaviour in the Managed Software Centre. This is especially frustrating when users want to install a new app but another install that requires restart or quitting Chrome is pending. The user is almost forced to defer, only to find that the app has been updated in background later.

**Comment by gregneagle** [comment] 2022-08-31 02:00
Not sure what you want here. `managedsoftwareupdate --auto` (normally) runs automatically in the background about once an hour, and Munki does install what it can.

The behavior you see in MSC.app is _intended_. I want users to install ALL the updates. If they want a new app, they must take the Chrome update, too.

Even if MSC.app optionally would behave the way I think you want, there'd be a UI/UX issue: MSC.app shows 10 updates, the user clicks "Update all" -- and not all would be updated. Maybe only one update is applied because the user has the other nine apps open. Now it shows nine updates and the user just thinks "Update all" is broken.

**Comment by ofirgalcon** [comment] 2022-08-31 02:13
I see. In this case you could display the current dialog that says that apps are open and can't be updates but add another button to update/install the rest.

Apple updates also allow you to update Safari while deferring updates that require restart.

**Comment by damluji** [comment] 2023-02-10 09:03
Exactly, have a "possible to deferr" tier for OS updates and such, so as not to block the rest. Its absurd to wait 30 minutes (or more, depending on download speeds) to install a small app because MSC has now refreshed and detected an OS update should be run.

**Comment by arubdesu** [comment] 2023-02-10 11:56
The absurdity can be lessened by your users installing updates in a reasonable time frame, offering less optional updates, choosing to not have apple updates managed by munki, or using the new default installs functionality and conversely allowing people to uninstall as needed. I used to have a service called moscargo to offer the contents of the munki repo for manual download as well.
Your opinion not being shared by all admins or the developer means either finding a way to contribute this feature or being patient are recommended things to do for now.

**Comment by damluji** [comment] 2023-02-10 12:48
That would be nice, except I AM a user, my admin pointed me to this thread. I patch my OS regularly but it was bad timing that I requested an app install right when macos 13.2 update dropped. And so, had to wait for the download to finish, then the obligatory restart before I could use the app to do my work.
It does make it less absurd, but does not completely fix the problem.

Thank you for your reply, I'll watch and wait, patiently, for this to be sorted out :)

**Comment by gregneagle** [comment] 2023-10-17 17:16
When there is an Apple update, when you click "Update" you are given an opportunity to skip the Apple update (at least if the Apple update has been available for a short time; after a few days the option to skip is removed). See the second screenshot here: https://github.com/munki/munki/wiki/manual-apple-updates-in-Munki-5

**Comment by gregneagle** [comment] 2023-10-17 17:18
I'm going to close this as MSC.app behaves as intended, and there have been no concrete proposals for alternative behaviors (it's hard to act on "I don't really like the way it behaves now"). If anyone can write a clear, implementable proposal for behavior changes we can start a new discussion.

**Closed by gregneagle** 2023-10-17 17:18 UTC
Labels: Feature Request
