### ISSUE TITLE
Password protect inside Managed Software Center - Munki2

### ISSUE THREAD

**Issue by jsummers1994** [munki/munki#762] opened 2017-05-04 09:05 UTC
Is there anyway of stopping users installing apps from within Managed software centre with a password? I want them to see the catalogue but not have the right to install which they currently have. Thank you.

**Comment by arubdesu** [comment] 2017-05-04 10:06
There is no concept of a directory service differentiating users, nor an auth mechanism. You can achieve this with a directory webpage instead, although I understand that's an out-of-band process that would require training/guiding users. I made a project in Flask that does this called Moscargo, there are others in Perl as well.

**Comment by jsummers1994** [comment] 2017-05-04 10:23
Thank you for your reply. I'm just struggling to understand why users can install apps through managed software centre, however when trying to install or make any other changes to the Mac OS they need admin credentials as they are not admin users. Thanks.

**Comment by arubdesu** [comment] 2017-05-04 10:32
They can because the included launchd jobs enable that behavior - Munki client software therefore runs as root, and that capability is explicitly called out on the overview and launchd job wiki pages. It is considered a feature, not a bug. If you don't want users installing the software, you would not make it available in the manifest.

**Comment by gregneagle** [comment] 2017-05-04 12:36
More importantly, that's the entire _point_ of the optional installs in Managed Software Center: items users can install for themselves. I understand that you want to use it instead as a convenient delivery mechanism for sneaker net techs to use, but that is not what it was designed for.

**Comment by gregneagle** [comment] 2017-05-04 12:39
There is no issue here as things are behaving as designed, so I will close this. Feel free to bring up the topic for discussion on the munki-discuss Google Group.

**Closed by gregneagle** 2017-05-04 12:39 UTC
