### ISSUE TITLE
Problem with Catalina 10.15 Beta 1 

### ISSUE THREAD

**Issue by g4fa** [munki/munki#938] opened 2019-06-09 09:01 UTC
No work anymore with Catalina 10.15 Beta

**Comment by arubdesu** [comment] 2019-06-09 12:20
Hello! Without logs or further description, it's hard to tell what you're actually having a problem with. You're also referencing a beta OS, which could change by the time it's released if it is the case that code changes are required for munki, so it may be early to file issues. 
In general this isn't where you'd get support where munki code changes aren't required, you're encouraged to post to the munki-discuss Google Group:
https://groups.google.com/group/munki-discuss

**Comment by gregneagle** [comment] 2019-06-09 16:05
I have seen some issues with the Catalina beta, but not too many. The biggest/most notable one I've seen is that when in bootstrapping mode after using installr to do a clean install of Catalina, the munkitools, and the munki_kickstart pkg, MunkiStatus does not appear, yet it appears `managedsoftwareupdate` is running in the background. 

Since "No work anymore" is too general (and not true, since it does work, with some issues) I'm going to close this. Please, if you find and can describe reproducible _specific_ issues, feel free to open new issues.

**Closed by gregneagle** 2019-06-09 16:05 UTC

**Comment by benstrattonwoodward** [comment] 2020-05-22 11:51
Hi Greg
I have the same issue as you, can you share how you resolved it?
Thanks in advance
Ben

**Comment by gregneagle** [comment] 2020-05-22 14:24
I don't know what "same issue" you have, but any issue I had almost a year ago was specific to the version of macOS and the version of Munki at the time. If you have a reproducible issue with the current Munki release, please open a new issue describing it.
