### ISSUE TITLE
Managed Software Center.app 4.1.2531 keeping GPU in High Perf.

### ISSUE THREAD

**Issue by childrss** [munki/munki#556] opened 2015-12-15 20:11 UTC
If Managed Software Center.app is open, the graphics card is kept in High Performance mode (discrete GPU, not the integrated mode).

This has ramifications as we've instructed our user base to "just minimize the MSC application or drag it to a corner" if you're doing a presentation and don't have time to run your updates yet but don't want it popping up again.

**Comment by gregneagle** [comment] 2015-12-15 20:18
MSC.app doesn't do anything special/explicit with the GPU. It does use a WebView for most of its UI; this might be an Apple issue if WebViews keep the GPU in high-performance mode for no good reason.

**Comment by keeleysam** [comment] 2015-12-24 07:26
Do you have any client customization?  There are certain elements that may cause this to happen but I haven't been able to reproduce with a stock client on my 2011 MacBook Pro with switching graphics.

**Comment by childrss** [comment] 2016-03-15 02:38
Yup.  We have some custom graphics.   Sorry for the delay in getting back on top of this :-(  I can research if further but it is not a big deal for us, just notice it.

**Comment by gregneagle** [comment] 2016-11-22 18:42
Closing this as there's not enough information to reproduce and it seems to be a WebView issue outside of Munki/Managed Software Center's control.

**Closed by gregneagle** 2016-11-22 18:42 UTC
