### ISSUE TITLE
Errors in 2.7

### ISSUE THREAD

**Issue by digitalhealer** [munki/munki#625] opened 2016-06-24 21:29 UTC
We are getting a weird error on about half of our machines after munkitools 2.7 upgrade.  They produce the following error on run.  dropping down to 2.6 fixes the issue

Exception RuntimeError: RuntimeError('maximum recursion depth exceeded while calling a Python object',) in <module 'threading' from '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.pyc'> ignored
Exception RuntimeError: RuntimeError('maximum recursion depth exceeded in __instancecheck__',) in <module 'threading' from '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.pyc'> ignored
ERROR: Unexpected error in updatecheck:
Traceback (most recent call last):
  File "/usr/local/munki/managedsoftwareupdate", line 1049, in <module>
    main()
  File "/usr/local/munki/managedsoftwareupdate", line 743, in main
    client_id=options.id.decode('UTF-8'))
  File "/usr/local/munki/munkilib/updatecheck.py", line 3054, in check
    installinfo)
  File "/usr/local/munki/munkilib/updatecheck.py", line 2170, in processManifestForKey
    processManagedUpdate(item, cataloglist, installinfo)
  File "/usr/local/munki/munkilib/updatecheck.py", line 1570, in processManagedUpdate
    is_managed_update=True)
  File "/usr/local/munki/munkilib/updatecheck.py", line 1824, in processInstall
    is_managed_update=is_managed_update)
  File "/usr/local/munki/munkilib/updatecheck.py", line 2049, in processInstall
    is_managed_update=is_managed_update)
  File "/usr/local/munki/munkilib/updatecheck.py", line 1824, in processInstall
    is_managed_update=is_managed_update)
  File "/usr/local/munki/munkilib/updatecheck.py", line 2049, in processInstall
    is_managed_update=is_managed_update)
  File "/usr/local/munki/munkilib/updatecheck.py", line 1824, in processInstall
    is_managed_update=is_managed_update)
  File "/usr/local/munki/munkilib/updatecheck.py", line 2049, in processInstall
    is_managed_update=is_managed_update)
  File "/usr/local/munki/munkilib/updatecheck.py", line 1824, in processInstall
    is_managed_update=is_managed_update)
  File "/usr/local/munki/munkilib/updatecheck.py", line 2049, in processInstall
    is_managed_update=is_managed_update)
  File "/usr/local/munki/munkilib/updatecheck.py", line 1824, in processInstall
    is_managed_update=is_managed_update)
  File "/usr/local/munki/munkilib/updatecheck.py", line 2049, in processInstall
    is_managed_update=is_managed_update)
  File "/usr/local/munki/munkilib/updatecheck.py", line 1824, in processInstall
    is_managed_update=is_managed_update)
  File "/usr/local/munki/munkilib/updatecheck.py", line 2049, in processInstall
    is_managed_update=is_managed_update)

**Comment by gregneagle** [comment] 2016-06-24 21:32
Is is possible you have circular references in one or more of your pkginfos?  Things like: Foo requires Bar which requires Foo, or Bar is an update_for Foo, which is an update_for Bar?

Based on the traceback, I'd be looking at items listed under managed_updates in the affected manifest(s).

**Comment by gregneagle** [comment] 2016-06-24 21:33
Running `/usr/local/munki/managedsoftwareupdate -vvv` on an affected client is likely to help you narrow down the cause more quickly.

**Comment by digitalhealer** [comment] 2016-06-24 21:45
that was it.  thanks for the quick reply

**Comment by gregneagle** [comment] 2016-06-24 21:46
Details on what you discovered might be helpful to see if there might be anything that can be done to warn admins about this issue or even work around it in some way.

**Comment by gregneagle** [comment] 2016-07-05 18:35
Closing due to no further communication from issue originator.

**Closed by gregneagle** 2016-07-05 18:35 UTC
