### ISSUE TITLE
munki import doesn't use CFPreferences

### ISSUE THREAD

**Issue by erikng** [munki/munki#638] opened 2016-07-15 23:13 UTC
Tracking this so I don't forget but munki import and all the other admin tools have a hard coded path to the user library. This makes automating a munki setup with mobile configuration files impossible.

**Comment by gregneagle** [comment] 2016-07-15 23:16
Not _impossible_... You could use mobile configuration files created with mcxToProfile with Set-Once (Once or Often) frequency if you need something to work today.

**Comment by gregneagle** [comment] 2016-07-15 23:18
Upon investigation, Munki Enterprise Support has determined this is a duplicate of issue #347.

**Closed by gregneagle** 2016-07-15 23:18 UTC

**Comment by erikng** [comment] 2016-07-15 23:22
Okay good idea. And that's hilarious.
