### ISSUE TITLE
Munki Crashes LoginWindow on first boot with CheckAndInstallAtStartup flag

### ISSUE THREAD

**Issue by Zolotkey** [munki/munki#752] opened 2017-04-18 19:05 UTC
On 10.11.4 and 10.12 Hosts, mainly 2015 5K iMacs and above. 

When you set the CheckAndInstallAtStartup file in /Users/Shared/ Munki launches too quick, and hangs the LoginWindow process. Munki still runs and installs. While the user sees, the system GUI hang at the macOS loading progress bar. You can ssh into the machine, and do 1 of 2 things. After the installs are finished you can reboot the computer and it will function normally. Or you can `killall LoginWindow` as root or sudo, and a new LoginWindow process will start and get you to the login screen as normal.

This has been repeatable on multiple iMacs.

If you want more info I can provide logs!

**Comment by gregneagle** [comment] 2017-04-22 05:02
We've had no other reports of anything like this. Can you provide a reproducible scenario?

**Comment by natewalck** [comment] 2017-05-08 13:22
Also, a screenshot/picture of the point where it gets stuck would be useful.

**Comment by gregneagle** [comment] 2017-05-08 15:10
This sounds like it might not be Munki at all, but rather an issue with the loginwindow. See: https://groups.google.com/d/msg/macenterprise/3Tw3nRvC6s8/JfYUe5g9BAAJ.

See also the script in this message:
https://groups.google.com/d/msg/munki-dev/E_URujCwig4/11ZSuVHBHQAJ

**Comment by gregneagle** [comment] 2017-05-08 16:01
Another possibly related thread:
https://www.jamf.com/jamf-nation/discussions/19988/stuck-on-startup

**Comment by gregneagle** [comment] 2017-06-14 17:30
Closing since it's not reproducible and not reported by others and it's been over a month since any new information has been added. Feel free to reopen if new information becomes available.

**Closed by gregneagle** 2017-06-14 17:30 UTC
