### ISSUE TITLE
managedsoftwareupdate not processing items from all catalogs

### ISSUE THREAD

**Issue by erikng** [munki/munki#470] opened 2015-04-06 15:54 UTC
foo is in production and testing catalog. Testing catalog has newer version.
manifest 1 - contains foo. no catalogs listed
manifest 2 - includes manifest 1. no catalogs listed.
manifest 3 (ClientIdentifier) - includes manifest 2. production and testing catalogs listed.

managedsoftwareupdate -vvvv (production catalog is first listed catalog)
Client sees 1 item to process foo-1.0 from production catalog

managedsoftwareupdate -vvvv (testing catalog is first listed catalog)
Client sees 1 item to process foo-1.1 from testing catalog

Client should see 2 items and process foo-1.1. Instead it is only looking at the first listed catalog.

Greg, I can provide logs and additional information, but I will need to send directly.

**Comment by gregneagle** [comment] 2015-04-06 15:58
That is the expected behavior.

https://github.com/munki/munki/wiki/Manifests#catalogs
"The catalogs are searched in order, but any valid match stops the search, so in the below example, a matching item in the testing catalog would stop the search - the production catalog would not be searched."

Munki doesn't search all the catalogs and then decide what is the "best" match -- it searches the first catalog for a match. If no match, it then proceeds to the next catalog, and so on.

This behavior is not related to included manifests; it's the normal catalog behavior.

**Comment by keeleysam** [comment] 2015-04-06 16:02
This is expected and documented behavior, you should list testing catalogs
first.

https://code.google.com/p/munki/wiki/MunkiCatalogDocumentation

On Monday, April 6, 2015, Erik Gomez <notifications@github.com> wrote:

> foo is in production and testing catalog. Testing catalog has newer
> version.
> manifest 1 - contains foo. no catalogs listed
> manifest 2 - includes manifest 1. no catalogs listed.
> manifest 3 (ClientIdentifier) - includes manifest 2. production and
> testing catalogs listed.
>
> managedsoftwareupdate -vvvv (production catalog is first listed catalog)
> Client sees 1 item to process foo-1.0 from production catalog
>
> managedsoftwareupdate -vvvv (testing catalog is first listed catalog)
> Client sees 1 item to process foo-1.1 from testing catalog
>
> Client should see 2 items and process foo-1.1. Instead it is only looking
> at the first listed catalog.
>
> Greg, I can provide logs and additional information, but I will need to
> send directly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/munki/munki/issues/470>.
>


-- 
Samuel Keeley

**Comment by erikng** [comment] 2015-04-06 16:09
:/

Thanks Sam.

**Comment by erikng** [comment] 2015-04-06 16:12
Is there a particular reason as to why?

Since MSU downloads all the catalogs available to its client, could it be an enhancement to auto merge the catalogs into one file "client all"? This could then drop that requirement.

**Comment by gregneagle** [comment] 2015-04-06 16:15
At this point, it really doesn't matter. This is the documented behavior. Changing it could break someone who is relying on it.

The documented behavior is that catalog order matters and Munki searches the catalogs in order, stopping when it finds the first applicable match.

I don't see a compelling reason to change the documented behavior. I _like_ that there is catalog precedence.

**Comment by erikng** [comment] 2015-04-06 16:20
Fair enough. I will create a conditional entry on my own backend that takes into account users who want to be "testers". 

I apologize for not knowing this behavior.

**Comment by gregneagle** [comment] 2015-04-06 16:21
Why not add the testing catalog as the first entry in the catalogs list of the primary manifest for these users?

**Comment by erikng** [comment] 2015-04-06 16:24
That's what I'm going to do. My current setup only adds a production catalog to their manifest so I was manually adding the testing catalog. Some had production first while others had testing and it didn't creep up until today. 

I shouldn't be manually modifying these test machines' manifests directly anyway.

**Comment by gregneagle** [comment] 2015-04-06 16:30
Closing this since there is no issue to address.

**Closed by gregneagle** 2015-04-06 16:30 UTC
