### ISSUE TITLE
Bootstrap mode triggered on setup assistant

### ISSUE THREAD

**Issue by kingslek** [munki/munki#839] opened 2018-02-15 17:17 UTC
We deploy Munki as a DEP bootstrap package with AirWatch - Munki's bootstrap mode enabled -
 Package created with DEP script available in Munki source code.  

In some scenarios (2017 MBP touchbar macOS 10.12.4) after the airwatch enrollment completes, we occasionally restart the device even though setup assistant is not completed, we then see the Munki bootstrap window above/in front of Setup Assistant. We think this should not happen. Munki should wait until macOS login window and not start during Setup Assistant. 

Thanks!

**Comment by gregneagle** [comment] 2018-02-15 17:19
_You_ are in control of bootstrap mode. If you don't want it, remove the bootstrap flag file, or don't include it with your DEP package.

**Comment by ygini** [comment] 2018-02-15 17:26
Hi @gregneagle, I’m the architect behind this setup. 

My understanding of bootstrap mode is that it should run at next start but only on the login window. 

I was thinking that bootstrap mode was designed to not run over Setup Assistant.

Am I wrong? Is it expected for bootstrap mode to run over Setup Assistant?

**Comment by gregneagle** [comment] 2018-02-15 17:31
The bootstrap mode is triggered by a LaunchAgent that runs in the loginwindow context.:

https://github.com/munki/munki/blob/master/launchd/LaunchAgents/com.googlecode.munki.managedsoftwareupdate-loginwindow.plist

Notice especially https://github.com/munki/munki/blob/master/launchd/LaunchAgents/com.googlecode.munki.managedsoftwareupdate-loginwindow.plist#L19-L22

That job has no conception of what else might be loaded over the loginwindow.  Setup Assistant might be loaded over the loginwindow....  But again: _you_ control if Setup Assistant might run at first boot. If you are _not_ disabling the Setup Assistant at first boot, then setting Munki into bootstrap mode at first boot might not be a good choice.

**Comment by ygini** [comment] 2018-02-15 17:37
The point is, we need bootstrap, but we would like it after Setup Assistant. So my understanding of it is incomplete. 

I was thinking it was a bug based on how I’ve understood it in first place. That’s why I’ve asked my friend to open an issue.

**Comment by gregneagle** [comment] 2018-02-15 18:19
So this issue can be closed?

**Comment by ygini** [comment] 2018-02-15 18:40
Except if you want me to implement a solution for the bootstrap to wait for the end of SetupAssistant, yes you can close it. Otherwise I will close it with the PR

**Comment by gregneagle** [comment] 2018-02-15 19:15
Typically when Setup Assistant ends, the user is logged into the newly-created account. The loginwindow LaunchAgent is unloaded, and any managedsoftwareupdate session launched via that LaunchAgent would be killed. Do you have a proposal on how to effectively bootstrap at first boot when Setup Assistant is not suppressed?

**Comment by ygini** [comment] 2018-02-15 19:19
Not yet, but if you're interested by such a scenario, I can look for it. Not sure if possible or not. 

Our scenario here is linked to Mac bound to the directory services and DEP creating the auto admin account. So Setup Assistant will in the end leave us to the login window. 

But I understand that's a specific scenario here and if we do something, we must do it for all.

**Comment by gregneagle** [comment] 2018-02-15 19:22
This could possibly be solved for your specific needs by a Munki preflight script that checks to see if Setup Assistant is running; if so it sleeps a second or so and checks again. Once Setup Assistant exits, the preflight exits and then Munki continues its run. This of course assumes that Setup Assistant is running _before_ the loginwindow LaunchAgent starts the managedsoftwareupdate process; which I'm not sure is guaranteed.

**Comment by ygini** [comment] 2018-02-15 19:27
Does preflight script is called before the UI being shown? If so, yes I can go that way and leave Munki's source code alone :-)

**Comment by gregneagle** [comment] 2018-02-15 19:29
UI is controlled by a different LaunchAgent. You might need to get clever in this preflight script and stop/start the job as needed.

**Comment by ygini** [comment] 2018-02-15 19:30
OK, so we can close the issue and keep this fix internal only since it seems to be too specific here

**Closed** 2018-02-15 19:59 UTC
