### ISSUE TITLE
Skip launch of MSC if mac is in fullscreen / mirroring to TVs and projectors

### ISSUE THREAD

**Issue by thomasm2film** [munki/munki#673] opened 2016-10-14 07:30 UTC
Hey Greg - nice talking to you during the Mac Sys Admin.

We often use macs for Keynote presentations - or playback in Adobe Premiere.

And two times, keynotes with video were halted and pushed out of fullscreen because "Managed Software Center" launched and made itself the foreground app. A bit embarrassing for the presenter.

Perhaps it could be possible to implement "Skip launch of MSC if mac is in fullscreen" feature? Just like the "Turn on Do Not Disturb when mirroring to TVs and projectors" inside Notifications preferences?

Thanks

**Comment by thomasm2film** [comment] 2016-10-14 08:11
Sorry, I saw that someone else have already posted about this.

Perhaps actual mirroring can be detected with:

system_profiler SPDisplaysDataType | grep Mirror

**Comment by gregneagle** [comment] 2016-10-14 13:58
Even if one can reliably detect mirroring (and I know you can): when I present with Keynote: I _don't_ use mirroring. Slides go to the projector, and a "presenters" screen is on the laptop screen.

This is a difficult problem to solve 100%, or even 90%.
See also https://github.com/munki/munki/wiki/FAQ#q-will-munki-pop-up-notifications-if-a-user-is-doing-a-presentation-in-front-of-an-audience and https://github.com/munki/munki/issues/655

**Comment by gregneagle** [comment] 2016-10-18 21:47
Closing this as a duplicate of #655

**Closed by gregneagle** 2016-10-18 21:47 UTC
