### ISSUE TITLE
APFS DMGs don't cleanly unmount

### ISSUE THREAD

**Issue by russellhancox** [munki/munki#831] opened 2018-01-25 02:11 UTC
This isn't an issue specific to Munki and doesn't cause any harm but I figured it's something people are likely to run in while using Munki and may wonder what's going on.

When attaching a disk image containing an APFS volume 2 devices are attached - the container and the volume. E.g.:

```
/dev/disk6          	GUID_partition_scheme
/dev/disk6s1        	Apple_APFS
/dev/disk7          	EF57347C-0000-11AA-AA11-0030654
/dev/disk7s1        	41504653-0000-11AA-AA11-0030654	/Volumes/mypackage-1.0
```

Unmounting using the volume (via its device ID or the mount path) doesn't unmount these disks correctly, so they continue to show up in `hdiutil info` and `diskutil list` output:

```shell
$ hdiutil detach /Volumes/mypackage-1.0
"disk7" unmounted.
"disk7" ejected.
$ diskutil list
<elided>
/dev/disk6 (disk image):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        +10.7 MB    disk6
   1:                 Apple_APFS Container disk7         10.7 MB    disk6s1

/dev/disk7 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +10.7 MB    disk7
                                 Physical Store disk6s1
   1:                APFS Volume mypackage-1.0           208.9 KB   disk7s1
```

The only way I've found to eject them properly is to eject the container:

```shells
$ hdiutil detach disk6
"disk6" unmounted.
"disk6" ejected.
```

Disk images created without specifying the filesystem (using e.g. ```-fs "Journaled HFS+"```) default to the same filesystem as the source files, so as admins upgrade to APFS themselves more APFS images will be created.

**Comment by erikng** [comment] 2018-01-25 02:13
This would explain why a package I had at one point was misbehaving.

Thanks,
Erik Gomez
________________________________

**Comment by gregneagle** [comment] 2018-01-25 02:13
Since this isn't a Munki issue, I'm going to close this. I do think it's useful information, and would encourage you to post it on the munki-discuss list.

**Closed by gregneagle** 2018-01-25 02:13 UTC

**Comment by gregneagle** [comment] 2018-01-25 02:15
(this really seems like a bug _Apple_ should address)

**Comment by erikng** [comment] 2018-01-25 02:16
Hm wouldn't this be an issue though? If you use an app wrapped dmg that is APFS munki wouldn't cleanly unmount.

Thanks,
Erik Gomez
________________________________

**Comment by erikng** [comment] 2018-01-25 02:16
Ah fair point.

Thanks,
Erik Gomez
________________________________

**Comment by gregneagle** [comment] 2018-01-25 02:24
There's no _need_ to use APFS disk images with Munki; the tools that ship with Munki (namely `munkiimport`) don't generate APFS disk images; autopkg .munki recipes do not generate APFS images. You kind of have to go out of your way to use APFS images with Munki. I'm inclined to react like "Doctor, it hurts when I do this." "Then don't do that."  If someone motivated would want to contribute a patch that detected APFS images and did the extra work to unmount them (and also handled them correctly on OSes prior to 10.13) I'd consider merging it. But it's not work I'm interested in/motivated to do when the problem is trivially avoided.

**Comment by russellhancox** [comment] 2018-01-25 02:53
> (this really seems like a bug Apple should address)

I concur. I won't hold my breath.

> You kind of have to go out of your way to use APFS images with Munki

Given that hdiutil's default behavior when no FS is specified is to use the source filesystem, I wouldn't say it's going that far out of your way _but_ yeah, I don't think it's worth any effort to handle this in Munki.

**Comment by russellhancox** [comment] 2018-01-25 02:55
(And for anyone else that cares, I've opened a [PR](https://github.com/unixorn/luggage/pull/65) with TheLuggage to default to HFS+ images)

**Comment by erikng** [comment] 2018-01-25 03:04
FWIW, the package in question was the official git package. I informed the maintainer for macOS and he released a patch a few weeks ago, but this would have impacted anyone using the autopkg recipe or manually imported.

Perhaps autopkg or munkiimport could give a warning when importing an APFS dmg.

Thanks,
Erik Gomez
________________________________

**Comment by gregneagle** [comment] 2018-01-25 03:15
A warning from munkiimport seems appropriate. As for the git package, it arguably should not be wrapped in a dmg at all

**Comment by erikng** [comment] 2018-01-25 03:17
Yeah there wasn't a need and that's ultimately what I did to fix the issue. Had to fix it anyone as it was resulting in munki errors in 10.12 machines.
